name = "AttributeGraphs"
uuid = "d091dd56-f8c5-469d-b7f7-ff847498145f"
authors = ["fchrstou <filippos.christou@ikr.uni-stuttgart.de> and contributors"]
version = "0.3.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"

[compat]
julia = "1.8"
DocStringExtensions = "0.9"
Graphs = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]